# Generated by Django 3.2 on 2022-03-17 21:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('guestprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestprofile',
            name='guest_number',
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='profile_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
