# Generated by Django 3.2 on 2022-03-17 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestprofile', '0002_auto_20220317_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestprofile',
            name='profile_id',
        ),
    ]
