# Generated by Django 3.2 on 2022-03-06 01:18

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('apartment_name', models.CharField(choices=[('Tony', 'Tony Apartment for max4 people'), ('Matea', 'Matea apartment for max4 people'), ('Martina', 'Martina apartment for max6 people')], max_length=10, primary_key=True, serialize=False)),
                ('beds_nr', models.IntegerField()),
                ('kitchen', models.BooleanField(default=True)),
                ('balcony', models.BooleanField(default=True)),
                ('seaview', models.BooleanField(default=True)),
                ('AC', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('ph_number', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{3}-\\d{4}$')])),
                ('email', models.EmailField(max_length=254)),
                ('kids', models.BooleanField(blank=True, default=False)),
                ('pets', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FrontPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='front_image')),
                ('related_to_apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_num', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('booking_created_on', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.apartment')),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.guest')),
            ],
        ),
        migrations.CreateModel(
            name='AddMorePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_images', cloudinary.models.CloudinaryField(max_length=255, verbose_name='more_images')),
                ('related_to_apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.apartment')),
                ('related_to_front_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.frontphoto')),
            ],
        ),
    ]
