# Generated by Django 3.2 on 2022-03-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
