# Generated by Django 3.2 on 2022-03-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_auto_20220306_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guest_id',
            new_name='guest_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_approved',
            field=models.BooleanField(default=False),
        ),
    ]
