# Generated by Django 3.2 on 2022-03-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0004_auto_20220306_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='front_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='front_image'),
        ),
    ]
