# Generated by Django 3.2 on 2022-03-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0005_apartment_front_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='front_image',
            field=models.ImageField(null=True, upload_to='static/media', verbose_name='front_image'),
        ),
    ]
