# Generated by Django 3.2 on 2022-03-09 20:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0006_alter_apartment_front_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='front_image2',
            field=cloudinary.models.CloudinaryField(default='second_img', max_length=255, verbose_name='front_image2'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='front_image3',
            field=cloudinary.models.CloudinaryField(default='third_img', max_length=255, verbose_name='front_image3'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='front_image',
            field=cloudinary.models.CloudinaryField(default='first_img', max_length=255, verbose_name='front_image'),
        ),
    ]
