# Generated by Django 3.2 on 2022-03-17 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestprofile', '0001_initial'),
        ('bookingapp', '0008_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='guest_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GuestProfile', to='guestprofile.guestprofile'),
        ),
    ]
