# Generated by Django 3.2 on 2022-03-17 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestprofile', '0003_remove_guestprofile_profile_id'),
        ('bookingapp', '0009_apartment_guest_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='guest_id',
            new_name='guest',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='guest_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GuestProf', to='guestprofile.guestprofile'),
        ),
    ]
