# Generated by Django 3.2 on 2022-03-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0010_auto_20220317_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='end_date',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='start_date',
            new_name='check_out',
        ),
    ]
