# Generated by Django 3.2 on 2022-03-30 16:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0012_auto_20220330_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='front_image4',
            field=cloudinary.models.CloudinaryField(default='third_img', max_length=255, verbose_name='front_image4'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='front_image5',
            field=cloudinary.models.CloudinaryField(default='third_img', max_length=255, verbose_name='front_image5'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='front_image6',
            field=cloudinary.models.CloudinaryField(default='third_img', max_length=255, verbose_name='front_image6'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='front_image7',
            field=cloudinary.models.CloudinaryField(default='third_img', max_length=255, verbose_name='front_image7'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='front_image8',
            field=cloudinary.models.CloudinaryField(default='third_img', max_length=255, verbose_name='front_image8'),
        ),
    ]
