# Generated by Django 3.2 on 2022-03-23 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_auto_20220315_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
